language: php
sudo: false
services:
    - mysql

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

env:
  global:
    - DATABASE_URL_TEST="mysql://root:@127.0.0.1:3306/P8_TEST"
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - CC_TEST_REPORTER_ID=8cc736ca14652536b34920d3b7db54616adf91d29385bca3f9e29710e2c0f901

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
  - mysql -e 'CREATE DATABASE IF NOT EXISTS P8_TEST;'

install:
  # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - ./vendor/bin/simple-phpunit install
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -q --env=test

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  # this checks that the YAML config files contain no syntax errors
  - ./bin/console lint:yaml config
  # this checks that the Twig template files contain no syntax errors
  - ./bin/console lint:twig templates
  # this checks that Doctrine's mapping configurations are valid
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  - ./bin/phpunit $PHPUNIT_FLAGS ./tests/

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT