version: "3"

services:
  databasetodo:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - "3306:3306"
    networks:
      - dev
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_todo
    restart: always
    depends_on:
      - databasetodo
    ports:
      - "8082:80"
    environment:
      PMA_HOST: databasetodo
    networks:
      - dev

networks:
  dev:

volumes:
  db_data:
